xadmin01/xadmin01/user/urls.py
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('val/', views.getsqlval),
    path('tag', views.tag),
    path('updatadb', views.updatadb),
    path('deldb', views.deldb),
    path('upsql', views.upsql),
    path('delsql', views.delsql),
    path('val2/', views.getsqlval2),
    path('resql', views.resql),
    path('sendoa',views.sendoa)
]

xadmin01/xadmin01/xadmin01/urls.py
from django.contrib import admin
from django.urls import path,include
import xadmin
from . import views

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', xadmin.site.urls),
    path('my01/', views.r1),
    path('my02/', views.r2),
    path('my03/',views.mssql),
    path('test1',views.test1),
    path('cache/',views.testcatche),
    path('student/',views.student),
    path('love/',include('user.urls')),
    path('user/',include('user.urls'))
]

xadmin01/xadmin01/mysarly/models.py
from django.db import models

# Create your models here.
class Salary01(models.Model):
    choices = (('male', '男性'),('female', '女性'))
    周期 = models.TextField(blank=True, null=True)
    员工编号 = models.TextField(blank=True,choices = choices, null=True)
    平时加班时数 = models.FloatField(blank=True, null=True)
    周末加班时数 = models.FloatField(blank=True, null=True)
    节日加班时数 = models.FloatField(blank=True, null=True)
    有薪假时数 = models.FloatField(blank=True, null=True)
    法定假时数 = models.FloatField(blank=True, null=True)
    基本工资 = models.FloatField(blank=True, null=True)
    平均时薪 = models.FloatField(blank=True, null=True)
    法定日平均工资 = models.FloatField(blank=True, null=True)
    平时加班费 = models.FloatField(blank=True, null=True)
    公休日加班费 = models.FloatField(blank=True, null=True)
    节日加班费 = models.FloatField(blank=True, null=True)
    有薪假工资 = models.FloatField(blank=True, null=True)
    法定假工资 = models.FloatField(blank=True, null=True)
    最低工资补助 = models.FloatField(blank=True, null=True)
    计件工资 = models.FloatField(blank=True, null=True)
    全勤奖 = models.FloatField(blank=True, null=True)
    应发工资 = models.FloatField(blank=True, null=True)
    工龄奖 = models.FloatField(blank=True, null=True)
    公积金 = models.FloatField(blank=True, null=True)
    社保 = models.FloatField(blank=True, null=True)
    实发工资 = models.FloatField(blank=True, null=True)
    个税 = models.FloatField(blank=True, null=True)
    保健补助 = models.FloatField(blank=True, null=True)
    应税额 = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'salary01'
        verbose_name = u'部门工资'
        verbose_name_plural = verbose_name

xadmin01/xadmin01/user/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from datetime import datetime

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core import validators


# Create your models here.
class DataSet(models.Model):
    id = models.AutoField(primary_key=True) # id 会自动创建,可以手动写入
    dataset = models.CharField(db_column='dataset',default='其它数据库',max_length=100, verbose_name=u'数据集')
    database=models.CharField(db_column='database',max_length=100, blank=True, null=True, verbose_name=u'数据库名称')
    username= models.CharField(db_column='username',max_length=100, blank=True, null=True, verbose_name=u'用户名')
    passwd = models.CharField(db_column='passwd', max_length=100, blank=True, null=True, verbose_name=u'密码')
    ip=models.CharField(db_column='ip',max_length=100, blank=True, null=True, verbose_name=u'服务器地址')

    inputdate = models.DateTimeField(db_column='inputdate', blank=True, null=True, default=datetime.now,verbose_name=u'录入时间')
    remark=models.CharField(db_column='remark',max_length=100, blank=True, null=True, verbose_name=u'备注')
    class Meta:
        db_table = 'dataset'
        verbose_name = '数据集信息'
        verbose_name_plural = '数据集信息'
        managed = False
    def __str__(self):
        return self.dataset

class vsql(models.Model):
    id = models.AutoField(primary_key=True) # id 会自动创建,可以手动写入
    title=models.CharField(db_column='title',max_length=100, verbose_name=u'标题')
    inputdate = models.DateTimeField(db_column='inputdate', blank=True, null=True, default=datetime.now,verbose_name=u'录入时间')
    remark=models.CharField(db_column='remark',max_length=100, blank=True, null=True, verbose_name=u'备注')
    dataset = models.ForeignKey("DataSet",on_delete=models.CASCADE,related_name='sql',verbose_name=u'数据集')
    sql = models.TextField(db_column='sql', max_length=500, blank=True, null=True, verbose_name=u'脚本')
    class Meta:
        db_table = 'vsql'
        verbose_name = '数据脚本'
        verbose_name_plural = '数据脚本'



class Department(models.Model):
    depart_name = models.CharField(max_length=20, verbose_name='所属部门')
    depart_group = models.CharField(max_length=20, blank=True, null=True, verbose_name='部门小组')

    class Meta:
        verbose_name = u'部门信息'
        verbose_name_plural = verbose_name
        managed = False

    def __unicode__(self):
        return self.depart_name



class UserProfile(models.Model):
    gender = models.CharField(max_length=6, choices=(('male', u'男'), ('female', u'女')), default='male', verbose_name='性别')
    address = models.CharField(max_length=100, default=u'', null=True, blank=True, verbose_name='地址')
    phone = models.CharField(max_length=11, verbose_name='手机号')
    department = models.ForeignKey(Department, verbose_name='部门',on_delete=None)

    class Meta:
        verbose_name = u'用户信息'
        managed = False
    def __unicode__(self):
        return self.username

class EmailVerifyRecord(models.Model):
    email_choices = (
        ('register', u'注册'),
        ('forget', u'找回密码'),
    )
    code = models.CharField(max_length=20, verbose_name=u'验证码')
    email = models.EmailField(max_length=50, verbose_name=u'邮箱')
    send_type = models.CharField(choices=email_choices, max_length=10, verbose_name=u'验证码类型')
    send_time = models.DateTimeField(default=datetime.now, verbose_name=u'发送时间')
    class Meta:
        verbose_name = u'验证信息'
        managed = False
    def __unicode__(self):
        return self.code

class AutoUser(models.Model):
    uid = models.IntegerField(db_column='UID', blank=True, null=True)  # Field name made lowercase.
    user_id = models.CharField(db_column='USER_ID', max_length=40, blank=True, null=True)  # Field name made lowercase.
    user_name = models.CharField(db_column='USER_NAME', max_length=60, blank=True, null=True,verbose_name=u'用户名')  # Field name made lowercase.
    user_name_index = models.CharField(db_column='USER_NAME_INDEX', max_length=60, blank=True, null=True)  # Field name made lowercase.
    byname = models.CharField(db_column='BYNAME', max_length=20, blank=True, null=True)  # Field name made lowercase.
    useing_key = models.CharField(db_column='USEING_KEY', max_length=1, blank=True, null=True)  # Field name made lowercase.
    using_finger = models.CharField(db_column='USING_FINGER', max_length=1, blank=True, null=True)  # Field name made lowercase.
    password = models.CharField(db_column='PASSWORD', max_length=50, blank=True, null=True)  # Field name made lowercase.
    key_sn = models.CharField(db_column='KEY_SN', max_length=20, blank=True, null=True)  # Field name made lowercase.
    secure_key_sn = models.CharField(db_column='SECURE_KEY_SN', max_length=20, blank=True, null=True)  # Field name made lowercase.
    user_priv = models.IntegerField(db_column='USER_PRIV', blank=True, null=True)  # Field name made lowercase.
    user_priv_no = models.IntegerField(db_column='USER_PRIV_NO', blank=True, null=True)  # Field name made lowercase.
    user_priv_name = models.CharField(db_column='USER_PRIV_NAME', max_length=40, blank=True, null=True)  # Field name made lowercase.
    post_priv = models.CharField(db_column='POST_PRIV', max_length=1, blank=True, null=True)  # Field name made lowercase.
    post_dept = models.TextField(db_column='POST_DEPT', blank=True, null=True)  # Field name made lowercase.
    dept_id = models.IntegerField(db_column='DEPT_ID', blank=True, null=True)  # Field name made lowercase.
    dept_id_other = models.CharField(db_column='DEPT_ID_OTHER', max_length=100, blank=True, null=True)  # Field name made lowercase.
    view_dept_id = models.CharField(db_column='VIEW_DEPT_ID', max_length=100, blank=True, null=True)  # Field name made lowercase.
    view_uid = models.CharField(db_column='VIEW_UID', max_length=100, blank=True, null=True)  # Field name made lowercase.
    view_priv_id = models.CharField(db_column='VIEW_PRIV_ID', max_length=100, blank=True, null=True)  # Field name made lowercase.
    leave_dept = models.IntegerField(db_column='LEAVE_DEPT', blank=True, null=True)  # Field name made lowercase.
    sex = models.CharField(db_column='SEX', max_length=1, blank=True, null=True)  # Field name made lowercase.
    birthday = models.DateTimeField(db_column='BIRTHDAY', blank=True, null=True)  # Field name made lowercase.
    is_lunar = models.CharField(db_column='IS_LUNAR', max_length=1, blank=True, null=True)  # Field name made lowercase.
    tel_no_dept = models.CharField(db_column='TEL_NO_DEPT', max_length=50, blank=True, null=True)  # Field name made lowercase.
    fax_no_dept = models.CharField(db_column='FAX_NO_DEPT', max_length=50, blank=True, null=True)  # Field name made lowercase.
    add_home = models.CharField(db_column='ADD_HOME', max_length=200, blank=True, null=True)  # Field name made lowercase.
    post_no_home = models.CharField(db_column='POST_NO_HOME', max_length=50, blank=True, null=True)  # Field name made lowercase.
    tel_no_home = models.CharField(db_column='TEL_NO_HOME', max_length=50, blank=True, null=True)  # Field name made lowercase.
    mobil_no = models.CharField(db_column='MOBIL_NO', max_length=50, blank=True, null=True)  # Field name made lowercase.
    bp_no = models.CharField(db_column='BP_NO', max_length=50, blank=True, null=True)  # Field name made lowercase.
    email = models.CharField(db_column='EMAIL', max_length=50, blank=True, null=True)  # Field name made lowercase.
    oicq_no = models.CharField(db_column='OICQ_NO', max_length=50, blank=True, null=True)  # Field name made lowercase.
    icq_no = models.CharField(db_column='ICQ_NO', max_length=50, blank=True, null=True)  # Field name made lowercase.
    msn = models.CharField(db_column='MSN', max_length=200, blank=True, null=True)  # Field name made lowercase.
    avatar = models.CharField(db_column='AVATAR', max_length=20, blank=True, null=True)  # Field name made lowercase.
    call_sound = models.IntegerField(db_column='CALL_SOUND', blank=True, null=True)  # Field name made lowercase.
    last_visit_time = models.DateTimeField(db_column='LAST_VISIT_TIME', blank=True, null=True)  # Field name made lowercase.
    sms_on = models.CharField(db_column='SMS_ON', max_length=1, blank=True, null=True)  # Field name made lowercase.
    menu_type = models.CharField(db_column='MENU_TYPE', max_length=1, blank=True, null=True)  # Field name made lowercase.
    last_pass_time = models.DateTimeField(db_column='LAST_PASS_TIME', blank=True, null=True)  # Field name made lowercase.
    theme = models.IntegerField(db_column='THEME', blank=True, null=True)  # Field name made lowercase.
    shortcut = models.TextField(db_column='SHORTCUT', blank=True, null=True)  # Field name made lowercase.
    portal = models.CharField(db_column='PORTAL', max_length=20, blank=True, null=True)  # Field name made lowercase.
    panel = models.CharField(db_column='PANEL', max_length=1, blank=True, null=True)  # Field name made lowercase.
    online = models.IntegerField(db_column='ONLINE', blank=True, null=True)  # Field name made lowercase.
    on_status = models.CharField(db_column='ON_STATUS', max_length=1, blank=True, null=True)  # Field name made lowercase.
    attend_status = models.CharField(db_column='ATTEND_STATUS', max_length=1, blank=True, null=True)  # Field name made lowercase.
    mobil_no_hidden = models.CharField(db_column='MOBIL_NO_HIDDEN', max_length=1, blank=True, null=True)  # Field name made lowercase.
    mytable_left = models.CharField(db_column='MYTABLE_LEFT', max_length=200, blank=True, null=True)  # Field name made lowercase.
    mytable_right = models.CharField(db_column='MYTABLE_RIGHT', max_length=200, blank=True, null=True)  # Field name made lowercase.
    user_priv_other = models.CharField(db_column='USER_PRIV_OTHER', max_length=100, blank=True, null=True)  # Field name made lowercase.
    user_no = models.IntegerField(db_column='USER_NO', blank=True, null=True)  # Field name made lowercase.

xadmin01/xadmin01/mysarly/views.py
from django.shortcuts import render

# Create your views here.

xadmin01/xadmin01/templates/mysarly.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<table border="1">
    <tr>
        <th>id</th>
        <th>员工编号</th>
        <th>应发工资</th>
        <th> 社保</th>
        <th>实发工资</th>
        <th>option</th>
    </tr>
    {% for book in all_book %}
    <tr>
        <td>{{ book.id }}</td>
        <td>{{ book.员工编号 }}</td>
        <td>{{ book.应发工资 }}</td>
        <td>{{ book.社保 }}</td>
        <td>{{ book.实发工资 }}</td>
        <td>
            <a href="/index/update_book/{{ book.id }}">更新</a>
            <a href="/index/delete_book/{{ book.id }}">删除</a>
        </td>
    </tr>
     {% endfor %}
    </table>
</body>
</html>

xadmin01/xadmin01/templates/result.html
<ul>
{% for choice in choices %}
    <li> {{ choice }} </li>
{% endfor %}
</ul>

xadmin01/xadmin01/templates/setdb.html
{% extends 'xadmin/base_site01.html' %}
{% block content %}
    <link rel="stylesheet" type="text/css" href="../../static/easyui/themes/default/easyui.css">
    <link rel="stylesheet" type="text/css" href="../../static/easyui/themes/icon.css">
    <link rel="stylesheet" type="text/css" href="../../static/easyui/themes/color.css">
    <link rel="stylesheet" type="text/css" href="../../static/easyui/demo/demo.css">
    <script type="text/javascript" src="../../static/easyui/jquery.min.js"></script>
    <script type="text/javascript" src="../../static/easyui/jquery.easyui.min.js"></script>
    <script type="text/javascript">
        $(function () {
            {% for id in db %}
                $("input[name='{{ id.name }}']").textbox({width: 120, type: 'text'})
            {% endfor %}

            $('#tt').datagrid({
                method: 'get',
                url: "../../love/val/",
                pagination: true,
                loadMsg: "aiiw正在努力加载数据，请稍后...",
                toolbar: "#tb",
                queryParams: {
                    sql: 'select * from dataset',
                    subject: 'datagrid'
                },

                singleSelect: true, //只允许选中一行

                columns: [
                    [{% for key,value in thead.items %}
                        {
                            field: '{{ key }}',
                            {#如下这个地方==前后要有空格#}
                            {% if key == 'ip' %}
                                width: 120,
                            {% elif key == 'inputdate' %}
                                width: 200,
                            {% else %}
                                width: 150,
                            {% endif %}
                            title: '{{ value }}'
                        },
                    {% endfor %}

                    ]
                ],
                onBeforeEdit: function (index, row) {
                    row.editing = true;
                    updateActions(index);
                },
                rownumbers: true, //添加了行号
                title: " 数据库集信息表",

                onClickRow: function (rowIndex, rowData) {
                    //两种方式,一是自动如下
                    $("tr[datagrid-row-index=" + rowIndex + "]").find("td").each(function () {
                        //alert($(this).text())
                        //alert($(this).attr('field'))
                        tab = $(this).attr('field')
                        //i=i+1
                        $('#id_'+tab).textbox('setValue', $(this).text());


                        //alert(i)
                    })
//$('#id_database').val(rowData.database);这个是原生态的赋值,如下是使用easyui的赋值
                    //方便二,手动
                    //$('#id_dataset').textbox('setValue', rowData.dataset);
                    // $('#id_database').textbox('setValue', rowData.database);
                    // $('#id_username').textbox('setValue', rowData.username);
                    // $('#id_passwd').textbox('setValue', rowData.passwd);
                    // $('#id_ip').textbox('setValue', rowData.ip);
                    // $('#id_inputdate').textbox('setValue', rowData.inputdate);
                    // $('#id_remark').textbox('setValue', rowData.remark);
                },


                {#这个地方是截止#}
            })


        })

        function del() {
            $.ajax({
                //几个参数需要注意一下
                type: "POST",//方法类型
                dataType: "text",//预期服务器返回的数据类型 如果是对象返回的是json 如果是字符串这里一定要定义text 之前我就是定义json 结果字符串的返回一直到额error中去
                url: "../../user/deldb",//url
                data: $('#myform1').serialize(),//这个是form表单中的id   jQuery的serialize()方法通过序列化表单值
                success: function (result) {
                    console.log("打印服务端返回的数据(调试用)");//打印服务端返回的数据(调试用)
                    {#console.log(result);//打印服务端返回的数据(调试用)#}
                    console.log(result);//打印服务端返回的数据(调试用)
                    ;
                    $('#tt').datagrid("reload");
                },
                error: function (s, s2, s3) {
                    alert("删除失败！");
                }
            });
            $('#tt').datagrid("reload");
        }

        function update1() {

            $.ajax({
                //几个参数需要注意一下
                type: "POST",//方法类型
                dataType: "text",//预期服务器返回的数据类型 如果是对象返回的是json 如果是字符串这里一定要定义text 之前我就是定义json 结果字符串的返回一直到额error中去
                /*
                dataType:
                    要求为String类型的参数，预期服务器返回的数据类型。如果不指定，JQuery将自动根据http包mime信息返回responseXML或responseText，并作为回调函数参数传递。可用的类型如下：
                    xml：返回XML文档，可用JQuery处理。
                    html：返回纯文本HTML信息；包含的script标签会在插入DOM时执行。
                    script：返回纯文本JavaScript代码。不会自动缓存结果。除非设置了cache参数。注意在远程请求时（不在同一个域下），所有post请求都将转为get请求。
                    json：返回JSON数据。
                    jsonp：JSONP格式。使用SONP形式调用函数时，例如myurl?callback=?，JQuery将自动替换后一个“?”为正确的函数名，以执行回调函数。
                    text：返回纯文本字符串。
                */
                url: "../../user/updatadb",//url
                data: $('#myform1').serialize(),//这个是form表单中的id   jQuery的serialize()方法通过序列化表单值
                success: function (result, status) {
                    console.log("打印服务端返回的数据(调试用)");//打印服务端返回的数据(调试用)
                    {#console.log(result);//打印服务端返回的数据(调试用)#}
                    console.log(result);//打印服务端返回的数据(调试用)
                    if (result.resultCode == 200) {//这个在这里没有用的,resultCode相当返回的结果集中的一个字体内容
                        alert("SUCCESS");
                    }
                    ;
                    $('#tt').datagrid("reload");
                },
                error: function (s, s2, s3) {
                    //数据成功传到后台 也有返回值 但就是报错 parsererror ：参考
                    https://blog.csdn.net/AinGates/article/details/75250223/

                        /*
                            写了一个ajax方法，后台一切正常，通过浏览器的F12工具查看XMLHttpRequest.status返回200，XMLHttpRequest.readyState返回4，也都没有问题。但是回调函数跳到error里，报parsererror的错误。经过排查，发现是因为后台返回时用了@ResponseBody注解（SpringMVC返回json格式的注解），但前台ajax提交没有定义dataType属性（定义服务器返回的数据类型）

                            还有一种情况是ajax方法中定义了 dataType:"json"属性，就一定要返回标准格式的json字符串，要不jQuery1.4+以上版本会报错的，因为不是用eval生成对象了，用的JSON.parse，如果字符串不标准就会报错。比如只返回一个简单的字符串“success”，“fail”， true，false，并不是标准的json字符串就会报错。

                                   首先，jQuery 1.4版本之后对服务端返回的JSON 数据要求比较严格，必须严格按照JSON的标准来了。
                        */

                        console.log(s)
                    console.log(s2)
                    console.log(s3)

                    alert("修改失败！");
                }
            });


        }


    </script>



    <div id="id1" class="easyui-panel" title="输入数据库信息集"
         style="width:auto;height:90px;padding:10px;background:#fafafa;"
         data-options="iconCls:'icon-save',closable:true,
    collapsible:true,minimizable:true,maximizable:true">

        <form METHOD="post" action="../setdb/" id="myform1">
            {% csrf_token %}
            {{ db }}

            <input type="submit">
            <button type="button" onclick="update1()">修改</button>
            <button type="button" onclick="del()">删除</button>
        </form>
    </div>

    <table id="tt" style="width:auto;height:500px">
    </table>



{% endblock %}

xadmin01/xadmin01/templates/sql.html
{% extends 'xadmin/base_site01.html' %}
{% block content %}
    <link rel="stylesheet" type="text/css" href="../../static/easyui/themes/default/easyui.css">
    <link rel="stylesheet" type="text/css" href="../../static/easyui/themes/icon.css">
    <link rel="stylesheet" type="text/css" href="../../static/easyui/themes/color.css">
    <link rel="stylesheet" type="text/css" href="../../static/easyui/demo/demo.css">
    <script type="text/javascript" src="../../static/easyui/jquery.min.js"></script>
    <script type="text/javascript" src="../../static/easyui/jquery.easyui.min.js"></script>
    <script type="text/javascript">
        $(function () {//这个地方,将普通的表单转为了easyui textbox
            $('#tt').draggable({disabled: false});
            $('#tt').datagrid({
                method: 'get',
                url: "../../love/val/",
                pagination: true,
                loadMsg: "aiiw正在努力加载数据，请稍后...",
                toolbar: "#tb",
                queryParams: {
                    sql: 'select t.*,d.dataset from vsql t left join dataset d on t.dataset_id=d.id',
                    subject: 'datagrid'
                },

                singleSelect: true, //只允许选中一行

                columns: [
                    [{% for key,value in thead.items %}
                        {
                            field: '{{ key }}',
                            {#如下这个地方==前后要有空格#}
                            {% if key == 'ip' %}
                                width: 120,
                            {% elif key == 'inputdate' %}
                                width: 200,
                            {% else %}
                                width: 150,
                            {% endif %}
                            title: '{{ value }}'
                        },
                    {% endfor %}

                    ]
                ],
                onBeforeEdit: function (index, row) {
                    row.editing = true;
                    updateActions(index);
                },
                rownumbers: true, //添加了行号
                title: " 数据库集信息表",

                onClickRow: function (rowIndex, rowData) {
                    //这条是可以用的$("select[name='dataset']").find("option[value='2']").attr("Selected",true);
                    $('#tt').datagrid("reload");
                    $("tr[datagrid-row-index=" + rowIndex + "]").find("td").each(function () {
                        //alert($(this).text())
                        //alert($(this).attr('field'))
                        tab = $(this).attr('field')
                        txt = $(this).text()
                        $("select[name='dataset'] option:contains('" + txt + "')").removeAttr("Selected")

                        if (tab != "dataset" && tab != "sql") {
                            $("input[name='" + tab + "']").attr("value", txt);
                            // $('#id_' + tab).text(txt);
                        } else if (tab == "sql") {
                            $("textarea[name='" + tab + "']").text(txt)
                        } else if (tab == "dataset") {
                            //$("select[name='dataset'] option:contains('" + txt + "')").get(2).selectedIndex=1;  //设置Select索引值为1的项选中
                            // $("select[name='dataset'] option:contains('" + txt + "')").attr("Selected", true);
                            $("select[name='dataset'] option:contains('" + txt + "')").attr("Selected", true);
                        }
                        //alert(tab+":"+$(this).text())
                        //alert(i)
                    })


//$('#id_database').val(rowData.database);这个是原生态的赋值,如下是使用easyui的赋值

                },
                {#这个地方是截止#}
            })


        })

        function del() {
            $.ajax({
                //几个参数需要注意一下
                type: "POST",//方法类型
                dataType: "text",//预期服务器返回的数据类型 如果是对象返回的是json 如果是字符串这里一定要定义text 之前我就是定义json 结果字符串的返回一直到额error中去
                url: "../../user/delsql",//url
                data: $('#myform1').serialize(),//这个是form表单中的id   jQuery的serialize()方法通过序列化表单值
                success: function (result) {
                    console.log("打印服务端返回的数据(调试用)");//打印服务端返回的数据(调试用)
                    {#console.log(result);//打印服务端返回的数据(调试用)#}
                    console.log(result);//打印服务端返回的数据(调试用)
                    ;
                    $('#tt').datagrid("reload");
                },
                error: function (s, s2, s3) {
                    alert("删除失败！");
                }
            });
            $('#tt').datagrid("reload");

        }

        function update1() {

            $.ajax({
                //几个参数需要注意一下
                type: "POST",//方法类型
                dataType: "text",//预期服务器返回的数据类型 如果是对象返回的是json 如果是字符串这里一定要定义text 之前我就是定义json 结果字符串的返回一直到额error中去
                /*
                dataType:
                    要求为String类型的参数，预期服务器返回的数据类型。如果不指定，JQuery将自动根据http包mime信息返回responseXML或responseText，并作为回调函数参数传递。可用的类型如下：
                    xml：返回XML文档，可用JQuery处理。
                    html：返回纯文本HTML信息；包含的script标签会在插入DOM时执行。
                    script：返回纯文本JavaScript代码。不会自动缓存结果。除非设置了cache参数。注意在远程请求时（不在同一个域下），所有post请求都将转为get请求。
                    json：返回JSON数据。
                    jsonp：JSONP格式。使用SONP形式调用函数时，例如myurl?callback=?，JQuery将自动替换后一个“?”为正确的函数名，以执行回调函数。
                    text：返回纯文本字符串。
                */
                url: "../../user/upsql",//url
                data: $('#myform1').serialize(),//这个是form表单中的id   jQuery的serialize()方法通过序列化表单值
                success: function (result, status) {
                    console.log("打印服务端返回的数据(调试用)");//打印服务端返回的数据(调试用)
                    {#console.log(result);//打印服务端返回的数据(调试用)#}
                    console.log(result);//打印服务端返回的数据(调试用)
                    if (result.resultCode == 200) {//这个在这里没有用的,resultCode相当返回的结果集中的一个字体内容
                        alert("SUCCESS");
                    }
                    ;
                    $('#tt').datagrid("reload");
                },
                error: function (s, s2, s3) {

                    alert("修改失败！");
                    $('#tt').datagrid("reload");
                }
            });


        }

    </script>



    <div id="id1" class="easyui-panel" title="输入数据库信息集"
         style="width:auto;height:90px;padding:10px;background:#fafafa;"
         data-options="iconCls:'icon-save',closable:true,
    collapsible:true,minimizable:true,maximizable:true">

        <form METHOD="post" action="../sql/" id="myform1">
            {% csrf_token %}
            {{ editsql }}
            <input type="hidden" name="id" maxlength="100" id="id_id">
            <input type="submit">
            <button type="button" onclick="update1()">修改</button>
            <button type="button" onclick="del()">删除</button>
        </form>
    </div>

    <table id="tt" style="width:auto;height:500px">
    </table>



{% endblock %}